Made little app
ISUCT/TProgramming_42_2018 pull request #26
Opened 2018-10-15 21:15 UTC by wbydc

2018-10-26 07:34 UTC, jskonst requested changes

2018-10-26 07:34 UTC, jskonst commented on CourseApp/Program.cs
> +            Dictionary<string, double> data = IO.read();
Давайте мы все таки не будем вычитывать из потока, если очень хочется разделить даные - вынесите их в отдельный файл и его прочитайте

2018-10-26 07:34 UTC, jskonst commented on CourseApp/Program.cs
> +            Dictionary<string, double> data = IO.read();
И почему вычитываем в Dict?

2018-10-26 07:34 UTC, jskonst commented on CourseApp/Program.cs
> +            Dictionary<string, double> data = IO.read();
Помните - это не руководство сразу поправить - можно пояснить свои действия

2018-10-26 07:34 UTC, jskonst commented on CourseApp/Program.cs
> +            Dictionary<string, double> answers = Solver.solve(data["a"], data["b"], data["xH"], data["xK"], data["dX"]);
Вы excel используете? не то чтобы это совсем не то..., похвальо, но это как микроскопом гвозди :)

2018-10-26 07:34 UTC, jskonst commented on CourseApp/Program.cs
> +            Dictionary<string, double> answers = Solver.solve(data["a"], data["b"], data["xH"], data["xK"], data["dX"]);
Используйте принцип - KIS - Keep It Simple

2018-10-26 07:34 UTC, jskonst commented on CourseApp/Program.cs
> +            double[] dataArr = IO.readArray();
Опять же - все здорово - но нет обработки ошибок, что если что-то пойдет не так при считывании?

2018-10-26 07:41 UTC, WannaBeYourDrug commented on CourseApp/Program.cs
> +            Dictionary<string, double> answers = Solver.solve(data["a"], data["b"], data["xH"], data["xK"], data["dX"]);
Извините, а при чём тут excel?

2018-10-26 07:42 UTC, WannaBeYourDrug commented on CourseApp/Program.cs
> +            Dictionary<string, double> data = IO.read();
В данном случае IO - это не поток, а отдельный класс для ввода-вывода, который на данный момент просто возвращает захардкоженные параметры

2018-10-26 07:43 UTC, WannaBeYourDrug commented on CourseApp/Program.cs
> +            double[] dataArr = IO.readArray();
Ничего не может пойти не так, по причине которую описал в другой ветке комментариев. Если потребуется чтение данных из потока/файла то валидацию сделаю в классе IO

2018-10-26 07:44 UTC, jskonst commented on CourseApp/Program.cs
> +            Dictionary<string, double> data = IO.read();
Кем захардкоженные и где храняться? в PR'е отсутствуют :(

2018-10-26 07:45 UTC, jskonst commented on CourseApp/Program.cs
> +            Dictionary<string, double> answers = Solver.solve(data["a"], data["b"], data["xH"], data["xK"], data["dX"]);
Solver.solve - если у вас импортируется некий Solver, то почему его опять же нет в PR'е?

2018-10-26 07:46 UTC, jskonst commented on CourseApp/Program.cs
> +            Dictionary<string, double> answers = Solver.solve(data["a"], data["b"], data["xH"], data["xK"], data["dX"]);
Точно все файлы присутствуют?, просто я всего может не вижу :(

2018-10-26 07:46 UTC, WannaBeYourDrug commented on CourseApp/Program.cs
> +            Dictionary<string, double> data = IO.read();
Прошу прощения, забыл включить их в коммит 😅
Сейчас залью

2018-10-26 07:47 UTC, jskonst commented on CourseApp/Program.cs
> +            double[] dataArr = IO.readArray();
Вооот, похоже все таки каких то файлов не хватает

2018-10-26 07:49 UTC, WannaBeYourDrug commented on CourseApp/Program.cs
> +            Dictionary<string, double> answers = Solver.solve(data["a"], data["b"], data["xH"], data["xK"], data["dX"]);
Залил недостающие файлы

2018-10-26 07:49 UTC, jskonst commented on CourseApp/Program.cs
> +            Dictionary<string, double> data = IO.read();
Ну слава богу - а то я уже думал все - пора на пенсию :( Магия какая-то происходит,

2018-10-26 15:45 UTC, WannaBeYourDrug commented
Так мне надо что-то менять?)

2018-11-11 22:44 UTC, jskonst commented on CourseApp/class/Solver.cs
> +        Dictionary<string, double> answer = new Dictionary<string, double>();
Как по мне так в таком варианте несколько избыточно испльзование словаря, вы можете в словаре похранить массив массивов, или использовать tuple, просто x тут вдруг становится строкой...

2018-11-11 22:44 UTC, jskonst commented on CourseApp/class/Solver.cs
> +        Dictionary<string, double> answer = new Dictionary<string, double>();
ТОчнее ключем в словаре ...

2018-11-11 22:45 UTC, jskonst commented on CourseApp.Tests/UnitTest1.cs
> +        public void Test1()
Файл теста пуст и ничего не выполняет - его надо либо добить - либу убрать из реквеста

2018-11-11 22:46 UTC, jskonst commented on CourseApp/class/IO.cs
> +        Dictionary<string, double> data = new Dictionary<string, double>();
Зачем все таки в этом случае использовать dictionary?

2018-11-12 09:02 UTC, WannaBeYourDrug commented on CourseApp/class/Solver.cs
> +        Dictionary<string, double> answer = new Dictionary<string, double>();
Про tuple даже не подумал, использовал уже знакомые конструкции

2018-12-14 23:09 UTC, jskonst requested changes
Подтяните изменения и stylecop

2018-12-18 07:08 UTC, jskonst requested changes
Проверка займет денек, но еще надо .... Тесты

2018-12-18 07:09 UTC, jskonst requested changes
И самое тяжелое, хотелось чтобы это все таки был core :(

2021-07-19 09:04 UTC, closed without merging