Added Test
ISUCT/TProgramming_42_2018 pull request #34
Opened 2018-10-27 17:07 UTC by FeLL1kS

2018-11-11 21:33 UTC, jskonst requested changes
Удалите ненужные папки, а ConsoleApp1.Tests переименуйте в ConsoleApp.Tests

2018-11-12 18:42 UTC, FeLL1kS commented
Название поменял, а ненужных папок вроде как и нет, во всех программы

2018-11-14 12:10 UTC, FeLL1kS commented
Удалил лишнее

2018-12-09 03:50 UTC, jskonst commented on CourseApp/Television.cs
> +        public byte channel { get; set; }
Свойства записываются с больщой буквы

2018-12-09 03:50 UTC, jskonst commented on CourseApp/Television.cs
> +        public byte model { get; set; }
а модель то почему байтом?

2018-12-09 03:51 UTC, jskonst commented on CourseApp/Television.cs
> +        public byte channel { get; set; }
А -1 канал можно включить?

2018-12-09 04:00 UTC, jskonst commented on CourseApp/Television.cs
> +        public string getInfo()
методы тоже с большой буквы начинаются

2018-12-09 11:35 UTC, FeLL1kS commented
Вроде всё исправил

2018-12-09 21:05 UTC, jskonst commented on CourseApp/Television.cs
> +        public int Channel { get; set; }
Еще бы провериять канал при установке свойства и + 1 тест - на установку отрицательного значения

2018-12-09 21:09 UTC, jskonst commented on CourseApp/Television.cs
> +        public int Channel { get; set; }
А еще непонятно назначение переменной check? Что ее инкрементируют, это ок, а зачем ее проверяете? Какая логика?

2018-12-09 21:16 UTC, FeLL1kS commented on CourseApp/Television.cs
> +        public int Channel { get; set; }
Проверяю на ошибку, если не равен нулю, то все впорядке и все выводится, иначе только вывод ошибки

2018-12-10 19:16 UTC, FeLL1kS commented
Переделал всё

2018-12-18 07:26 UTC, merged